# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GospeedServer < Formula
  desc "Speed test server for gospeed"
  homepage "https://gospeed.goozt.org"
  version "1.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed-server_1.3.3_darwin_amd64.tar.gz"
      sha256 "da7382e497fa0a5ebeb6341873ce06564c58dd1e7e3a5373ec10f97aec7186db"

      define_method(:install) do
        bin.install "gospeed-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed-server_1.3.3_darwin_arm64.tar.gz"
      sha256 "f85ed24a9e0d1c47e1a63f67589eb9930385a273969783f44ea7e26105defc42"

      define_method(:install) do
        bin.install "gospeed-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed-server_1.3.3_linux_amd64.tar.gz"
      sha256 "214d7d7d6074130b724f6ec8e2615dddb422257c3a7fa797146d83ec677a7864"
      define_method(:install) do
        bin.install "gospeed-server"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed-server_1.3.3_linux_arm.tar.gz"
      sha256 "d2d929444394c175ab9369cc21695b717c11f4e2e9d3c95fbf459ffad37146c0"
      define_method(:install) do
        bin.install "gospeed-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed-server_1.3.3_linux_arm64.tar.gz"
      sha256 "aab1d66182805bfc6e656f636c9ea6aa1bb65b843c6ad987edcf896bfb49482a"
      define_method(:install) do
        bin.install "gospeed-server"
      end
    end
  end
end
