# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gospeed < Formula
  desc "Fast, zero-dependency network speed testing tool"
  homepage "https://gospeed.goozt.org"
  version "1.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed_1.3.3_darwin_amd64.tar.gz"
      sha256 "7b7a9b081a8bff5d5251a3ae6ba38f2680db5684bbe4bb964b05f00e0539bc15"

      define_method(:install) do
        bin.install "gospeed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed_1.3.3_darwin_arm64.tar.gz"
      sha256 "7101aae92b64ab54e51b1dbffba81b184743e91fd6151d544e8ea0174d95492c"

      define_method(:install) do
        bin.install "gospeed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed_1.3.3_linux_amd64.tar.gz"
      sha256 "417a911ddb547f45947c0d1a1aa9f4de2299abada5777785bf081f34f142a89a"
      define_method(:install) do
        bin.install "gospeed"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed_1.3.3_linux_arm.tar.gz"
      sha256 "3d4da4973b901e57687d093a9ce46b9ff06672964ec33870bf6a2701f35d344e"
      define_method(:install) do
        bin.install "gospeed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed_1.3.3_linux_arm64.tar.gz"
      sha256 "b3fd7e4cbab4289e93d4283c4e43e3eaea33a4e9cb4ed64f8b86cc4b3e89ebe9"
      define_method(:install) do
        bin.install "gospeed"
      end
    end
  end
end
