# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gospeed < Formula
  desc "Fast, zero-dependency network speed testing tool"
  homepage "https://gospeed.goozt.org"
  version "1.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.4/gospeed_1.3.4_darwin_amd64.tar.gz"
      sha256 "5c9a1ea86daccbfa1b8e513d5f3495730890767e71743462803e9dcea42d436b"

      define_method(:install) do
        bin.install "gospeed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.4/gospeed_1.3.4_darwin_arm64.tar.gz"
      sha256 "00af787907d21bcd5c72d90535ee1ea115fb44c11e1f52908aba1c11862b69bd"

      define_method(:install) do
        bin.install "gospeed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.4/gospeed_1.3.4_linux_amd64.tar.gz"
      sha256 "e3f0eb6db0d645b6aabaa17866752ace67564e4259274805725c2b94643bbe40"
      define_method(:install) do
        bin.install "gospeed"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.4/gospeed_1.3.4_linux_arm.tar.gz"
      sha256 "891cf4de5a177794238022233d13e40e28517067cfa91797d567d122479646eb"
      define_method(:install) do
        bin.install "gospeed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.4/gospeed_1.3.4_linux_arm64.tar.gz"
      sha256 "61c05ef48d072fe63e70e76223611dcda4066167e9ddd1e0a725cc3f74ebed08"
      define_method(:install) do
        bin.install "gospeed"
      end
    end
  end
end
