# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GospeedServer < Formula
  desc "Speed test server for gospeed"
  homepage "https://gospeed.goozt.org"
  version "1.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed-server_1.3.3_darwin_amd64.tar.gz"
      sha256 "c5f442425b15a2efe2cb815243096998335ce68bd46623fd28b4515d684aecff"

      define_method(:install) do
        bin.install "gospeed-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed-server_1.3.3_darwin_arm64.tar.gz"
      sha256 "809f5dac781fa563a9c03218be4245838e94eb9a77d236baa1c2513ed6692654"

      define_method(:install) do
        bin.install "gospeed-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed-server_1.3.3_linux_amd64.tar.gz"
      sha256 "2b72d249816d3ebc1d26089ed6a7c9b6b113ac3c1c214df27bccbe83cd35325c"
      define_method(:install) do
        bin.install "gospeed-server"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed-server_1.3.3_linux_arm.tar.gz"
      sha256 "ef64c90bf767f8642852e4a8c9295a0b00ba95eb4e4cda34af3d1312360370e8"
      define_method(:install) do
        bin.install "gospeed-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed-server_1.3.3_linux_arm64.tar.gz"
      sha256 "5e24d343dd543017f831649aac5f5d5a87d27be371c159271411bd94f0368458"
      define_method(:install) do
        bin.install "gospeed-server"
      end
    end
  end
end
