# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gospeed < Formula
  desc "Fast, zero-dependency network speed testing tool"
  homepage "https://gospeed.goozt.org"
  version "1.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed_1.3.3_darwin_amd64.tar.gz"
      sha256 "4ef0d61daa0e83a6e1279250df32071591091a1ff8c93c4be1a21843cea095f8"

      define_method(:install) do
        bin.install "gospeed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed_1.3.3_darwin_arm64.tar.gz"
      sha256 "98bd9a1ac42b1ffecae54ca16fda54d81f1bb13436a9305dacc0ac13fdb2ffb6"

      define_method(:install) do
        bin.install "gospeed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed_1.3.3_linux_amd64.tar.gz"
      sha256 "079ca37b4442299e29e34294057505a0590338b1af30ea3ba07035c5d2f76686"
      define_method(:install) do
        bin.install "gospeed"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed_1.3.3_linux_arm.tar.gz"
      sha256 "974c5034eaf4562a6e2df23748edc124189b1d9f31e3ccb76513e1bd1eb579ae"
      define_method(:install) do
        bin.install "gospeed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goozt/gospeed/releases/download/v1.3.3/gospeed_1.3.3_linux_arm64.tar.gz"
      sha256 "252024b9823cc3425bab0af48b385552186cfacc74ce9210406e8958f00e3e49"
      define_method(:install) do
        bin.install "gospeed"
      end
    end
  end
end
